---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: docker-private-registry
  name: docker-private-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-private-registry
  template:
    metadata:
      labels:
        app: docker-private-registry
    spec:
      containers:
      - image: registry:2
        imagePullPolicy: IfNotPresent
        name: docker-private-registry
        env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:5000
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/cert.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/cert.key
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/registry
          name: image-store
        - mountPath: /certs
          name: certs
      volumes:
      - emptyDir: {} # THIS IS NOT PERSISTENT! WILL DELETE WITH POD!
        name: image-store
      - name: certs
        secret:
          secretName: registry-tls
          items:
          - key: tls.crt
            path: cert.crt
            mode: 256 # 0400 in decimal
          - key: tls.key
            path: cert.key
            mode: 256 # 0400 in decimal
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: docker-private-registry
  name: docker-private-registry
spec:
  ports:
  - nodePort: 30500
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: docker-private-registry
  type: NodePort

---
apiVersion: v1
kind: Secret
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVERENDQXZTZ0F3SUJBZ0lVYnVQY1pIZTNDNlNiK1g2ZUtMdHdwc29kMHVRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2NERUxNQWtHQTFVRUJoTUNWVk14RlRBVEJnTlZCQWdUREZCbGJtNXplV3gyWVc1cFlURVRNQkVHQTFVRQpCeE1LU0dGeWNtbHpZblZ5WnpFVE1CRUdBMVVFQ2hNS1MzVmlaWEp1WlhSbGN6RUxNQWtHQTFVRUN4TUNRMEV4CkV6QVJCZ05WQkFNVENrdDFZbVZ5Ym1WMFpYTXdIaGNOTWpBd01qSTBNakF6TXpBd1doY05NakV3TWpJek1qQXoKTXpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pWVXpFVk1CTUdBMVVFQ0JNTVVHVnVibk41YkhaaGJtbGhNUk13RVFZRApWUVFIRXdwSVlYSnlhWE5pZFhKbk1STXdFUVlEVlFRS0V3cExkV0psY201bGRHVnpNU0V3SHdZRFZRUUxFeGhMCmRXSmxjbTVsZEdWeklGUm9aU0JCYkhSaE15QlhZWGt3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUN2UU9waEcwcGpHaEhoQnY2WXViWFdlYjBIY1NmQ2xCbHVJeEh2eFl6Z1hINjAvZTFTTlhTTwoxSEdWTnpiTm12QUJmL0Yyb1ZqRUFSZmxHRUZUYmJXN3lwZmE5aXBiUUVmWVlGWFFDRGd1clNqdTZGbW1WUmxwCmZnSDhIZVc5elNQUDlXMTRRVVdCbmM0eThhK2NQYzNLTFBGQjdnWS9JanNJQndlVDl6ekg0bk1EOUYrOWM4MG0Kb0VZVlZMeU5xQXRyZEhZbVhCbFJZbzBHN0x6K1p5d09EeW1CbXBrVS96cEEvY0xuRkZqcEd1MGcvMUpmdENLYwo1VmdORjFuUVhMMWo2U1Qramd3emZzNXNmVS9sT2F2QVpCMUhkQ081OVFxbzZoeW5oaTQ4cDI5dE9oNjM1bGM3Cm5PVnJiaUgyRG5Ib09uL2JNQTByZEt3eEowOGNFekt2QWdNQkFBR2pnWnd3Z1prd0RnWURWUjBQQVFIL0JBUUQKQWdXZ01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQQpNQjBHQTFVZERnUVdCQlM2YVFYRUxqVXZMeld2MmIzaWpibGtRRnBQcWpBZkJnTlZIU01FR0RBV2dCUitsbmVICkhqUlArQ0MwdjdnQ1lqeVdnVDNvTURBYUJnTlZIUkVFRXpBUmdnbHNiMk5oYkdodmMzU0hCSDhBQUFFd0RRWUoKS29aSWh2Y05BUUVMQlFBRGdnRUJBRnpqTUh3L1gwVE1Oa3hFNHg0YjVKaDJ1V01GMmlmZXlPeXJ4cFdoMjBLaAo1b0cyczZsMC9lcndIeHBuYVJIT21kdUw4YnUyMWYyYnFlMUV2bzFOL245OVR1MUw0UW5qT3cwV0NReW9FdXY3CjJJMjloR2cwMW5FSjJ2R3c5VlF2bGUvTjRLMGY2UWErYWcrUWZEa25OT3Z6Yk1ycytyRHBoL3duSGsyQ3RienUKR00vMDd0MGtBazZwLzAzdTlFTGVkZGM1bUc1VEFveERVSkc5RVJZZmpKaXlCckRzZ0twZE1nbW9wOWF2UTJXego0M1hKNks5dEw3Z1pGS0lhR1JITWh3Z29mUEFWOVBOSHpac3dCN0R1bldGb3BFSUJFS2pjVDNiblhPeGlUeUtCCnJ6WXU0UERaZEdINVBSR3NVN1BORm80MXN6KzZTUC96emN2UTVOaStISzg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcjBEcVlSdEtZeG9SNFFiK21MbTExbm05QjNFbndwUVpiaU1SNzhXTTRGeCt0UDN0ClVqVjBqdFJ4bFRjMnpacndBWC94ZHFGWXhBRVg1UmhCVTIyMXU4cVgydllxVzBCSDJHQlYwQWc0THEwbzd1aFoKcGxVWmFYNEIvQjNsdmMwanovVnRlRUZGZ1ozT012R3ZuRDNOeWl6eFFlNEdQeUk3Q0FjSGsvYzh4K0p6QS9SZgp2WFBOSnFCR0ZWUzhqYWdMYTNSMkpsd1pVV0tOQnV5OC9tY3NEZzhwZ1pxWkZQODZRUDNDNXhSWTZScnRJUDlTClg3UWluT1ZZRFJkWjBGeTlZK2trL280TU0zN09iSDFQNVRtcndHUWRSM1FqdWZVS3FPb2NwNFl1UEtkdmJUb2UKdCtaWE81emxhMjRoOWc1eDZEcC8yekFOSzNTc01TZFBIQk15cndJREFRQUJBb0lCQUVaVStmckFsZ2pSaEkxWApYa055ZkJ3M3ZQbkltcGxIRURHWUYzR3ZTVXNkTTZoMUk1SFRiQlNLQTQ5TG1rM0hPVHlRMlJtdnhNemNWM2VVClZWc2k4MFVMR0FoQ3RGcnNvQ2lnK0s5RkxTN21SVUFqdFI3QWxqTTA0NTBIYnBUT1Irb0VaOHRUL28zM0E3S0UKTmVLeEZ1NWxQT2tsbWhJcUxhQ2FHWnR6SkV4ZTFhQnhCK09WUU9OU1hPQVpGeE53V2xjcGpSQ3RoM2JIWS8vMQpUOGlZa25aa05RaVE1TEwzWUJTQzJOdXpLSjlIaDRrK1dYb2xpSnNWajkrSDF5emhWcFFnVlNZV2JjR0Z5cEpNCldFbVlKZDFRdE13d0FUbnZ0QWRFMUtUUHhlYVFXWW85UlpZdGIzZFVOMERHU0ZmZjd2RDJ0ano2a3RkcEhScXgKandFbnlaRUNnWUVBMU5zWDJwQWo5OWRNYkppdS9ITi9Ja1hYb25lRVl2MEI1VDYrc21WMVBQYkM2aHpBNTg3dQowbVlaUURnTFBNOWFxQzhIU1Izb2U3dnV3VmRGcHhwMXZWU1Blb2pKTXdQLzVIYjJnaXBtbWZNaDhhZzB1QW9xClNPcFZkK2ZwemdmNUQ4cFhVN0UraTkxNUE0VG5razd5aGxBeXBURXNqWGIvNm1HOGViUUVML2tDZ1lFQTBzYXMKYWdpN2FhYnZvYitpTDY1NWFKOEU3SlEzUHE3TERkcDhTQk12S3FrQzEranZLL0lycXk2OHlOdFNuU0lJWXVxdwplbmpQR1pUcCsvbnlUR0FsUGNaL0FESzFuZlUwMTE0R295ZjdLcjZCdUJpMnNNa0FuTWxuMTFzMHZ4Q2R2Mi9rCjR6Q1l4UGNreUM5TUxidUc5Z2QyZTVtdXg4MEdGNXpWOUJIWGNlY0NnWUVBaGY2R1BhaVBlKzJreHBnM1QrVEYKRzZZcjRMS3NQRVJaZFI3U25Tc1JhcGRNakdRZGE4L3d0N0plSXZjazI5c01qdU5NQ3RNeER2TjNrVzZIQW5LOQp1N29IdUhOemRSSUhmS01HKzFvRnpOUXBnaDhKVVBIVlBLR0h2RHZhQzBFcG9LOFgyaSt4MkFwTHE5TjJrN3Z2CklHNUw4NEhKTWlTL1phU3hLVXdSZHNFQ2dZQXZiMURNQ0MwTlNPbHpFR3FTcW9SZVBETmlmclMwSWFoRzlOMjEKWnNQZHFPMmY0NmMzejZkdVBmVjBpbzljRjVXbGxVV2tPbDM1VnQ4VnV4bUJnTDNBMmxRb21rRHZUSWpZMHl0UgpPcVUyNkdyUElKaTB6bmVaMFdYU1BJOXhWRzc3NzFXbW40QXlDNkMyZ0paM1VGVytOczIrWVViSlptV3htTFU1CjJXNFFEd0tCZ0ZCN09ueFFTZ1l3OWdPUjZyczVRVm1QWDAzMks5Zk1MQUZvY2Q3SVpZVEF1ZjZ6U2c4YkxzWmoKbHV3TXdvNEUvRVlUeXc0SWtTL2J4YUdyMWg1bGpaMXRMcW9JcFMyMVRvZDRla0YyaHp1UitIdTFuTGdIbC9vdgplYWcrVWVWQjE1SGJHeXppbUdPWERFRkFVdXhWdzE1cXgrUko4aEorbnpyOUZMWklKY1dmCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
metadata:
  name: registry-tls
  namespace: default
type: Opaque
