apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"what":"what"},"name":"nginx","namespace":"default"},"spec":{"containers":[{"image":"nginx:1.7.9","name":"nginx","ports":[{"containerPort":80}]}]}}
  creationTimestamp: "2020-02-26T23:51:05Z"
  labels:
    app: web_service
    importance: critical
    customer: internal_use
    what: what
  name: nginx
  namespace: default
  resourceVersion: "304737"
  selfLink: /api/v1/namespaces/default/pods/nginx
  uid: e8a9e786-abf0-4cb7-9c59-6dca5d73e228
spec:
  containers:
  - image: nginx:1.7.9
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-pwmqq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-1428-node-01
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-pwmqq
    secret:
      defaultMode: 420
      secretName: default-token-pwmqq
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-02-26T23:51:05Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-02-26T23:51:32Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-02-26T23:51:32Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-02-26T23:51:06Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://d9050738d50c7091bd790a2850cd7fea543545fec77e76ae81c19e8b7a5a8606
    image: docker.io/library/nginx:1.7.9
    imageID: sha256:35d28df486f6150fa3174367499d1eb01f22f5a410afe4b9581ac0e0e58b3eaf
    lastState:
      terminated:
        containerID: containerd://46456fa2ed632df2262d2d93541aa58081ee2782a7c667b1f8c59e19adeb2280
        exitCode: 0
        finishedAt: "2020-02-26T23:51:31Z"
        reason: Completed
        startedAt: "2020-02-26T23:51:07Z"
    name: nginx
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: "2020-02-26T23:51:31Z"
  hostIP: 10.1.62.134
  phase: Running
  podIP: 192.168.215.151
  qosClass: BestEffort
  startTime: "2020-02-26T23:51:05Z"
