apiVersion: v1
kind: Pod
metadata:
  name: webservice01
  labels:
    name: webservice01
spec:
  containers:
  -
    name: webby
    image: reg.alta3.com/1428-purushothaman-webby
    ports:
     -
       name: web
       containerPort: 8888
       protocol: TCP
