apiVersion: v1
data:
  nginx.txt: "user  nginx;\nworker_processes  1;\nerror_log  /var/log/nginx/error.log
    warn;\npid        /var/run/nginx.pid;\nevents {\n    worker_connections  1024;\n}\nhttp
    {\n    include       /etc/nginx/mime.types;\n    default_type  application/octet-stream;\n
    \   log_format  main  '$remote_addr - $remote_user [$time_local] \"$request\"
    '\n                      '$status $body_bytes_sent \"$http_referer\" '\n                      '\"$http_user_agent\"
    \"$http_x_forwarded_for\"';\n    access_log  /var/log/nginx/access.log  main;\n
    \   sendfile        on;\n    keepalive_timeout  65;\n    server {\n        server_name
    \ localhost;\n        listen 80;\n        root /var/www;\n\n        location /
    {\n          sendfile  on;\n          index index.html;\n        }\n    location
    /static {\n\tautoindex on;\n\t}\n    }\n}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2020-02-27T20:01:04Z"
  name: nginx-txt
  namespace: default
  resourceVersion: "423724"
  selfLink: /api/v1/namespaces/default/configmaps/nginx-txt
  uid: 0e287686-8af8-4031-891d-fb40fea8d63a
